
export const LAYOUT_CONFIG = {
  SECTION_WIDTH: 400,
  SECTION_SPACING: 80,
  VERTICAL_SPACING: 80,
  START_Y: 50,
} as const;

export const POSITIONS = {
  BEFORE_X: 50,
  get TRANSACTION_X() { return this.BEFORE_X + LAYOUT_CONFIG.SECTION_WIDTH + LAYOUT_CONFIG.SECTION_SPACING; },
  get AFTER_X() { return this.TRANSACTION_X + LAYOUT_CONFIG.SECTION_WIDTH + LAYOUT_CONFIG.SECTION_SPACING; },
} as const;

export const Y_POSITIONS = {
  SECTION_HEADER_Y: LAYOUT_CONFIG.START_Y,
  ACQUIRING_HEADER_Y: LAYOUT_CONFIG.START_Y + 60,
  CONTROLLING_SHAREHOLDER_Y: LAYOUT_CONFIG.START_Y + 110,
  ACQUIRING_COMPANY_Y: LAYOUT_CONFIG.START_Y + 190,
  TARGET_HEADER_Y: LAYOUT_CONFIG.START_Y + 310,
  TARGET_SHAREHOLDERS_Y: LAYOUT_CONFIG.START_Y + 360,
  TARGET_COMPANY_Y: LAYOUT_CONFIG.START_Y + 440,
} as const;
