
export const ENTITY_WIDTH = 200;
export const ENTITY_HEIGHT = 90;
export const LEVEL_Y_SPACING = 180;
export const SIBLING_X_SPACING = ENTITY_WIDTH + 50;
export const SECTION_X_SPACING = ENTITY_WIDTH + 150;

export const BASE_Y_SHAREHOLDER = 50;
export const BASE_Y_COMPANY = BASE_Y_SHAREHOLDER + LEVEL_Y_SPACING;
export const BASE_Y_CONSIDERATION = BASE_Y_COMPANY + LEVEL_Y_SPACING;
export const BASE_Y_SUBSIDIARY = BASE_Y_COMPANY + LEVEL_Y_SPACING;
