// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zujiytxffcllxcdpzzyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1aml5dHhmZmNsbHhjZHB6enluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDM5OTIsImV4cCI6MjA2MTQxOTk5Mn0.fntsXkYETW_soxas3XbjMJdgaj_P-IGcYzEMdEAUC30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);